/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zoo;

/**
 *
 * @author akamojo
 */
public class BiletyFrame extends javax.swing.JFrame {

    /**
     * Creates new form BiletyFrame
     */
    public BiletyFrame() {
        initComponents();
        setIconImage(Zoo.getIcon());
        String[] columns = new String[]{"Numer", "Wiek klienta", "Czas sprzedaży", "Id sprzedawcy", "Typ biletu"};
        CacheSqlTableModel model = new CacheSqlTableModel("select * from bilety", columns, "ORDER BY NR");
        biletyTable.setModel(model);
        biletyTable.removeColumn(biletyTable.getColumnModel().getColumn(0));
    }

    public void refresh() {
        String[] columns = new String[]{"Numer", "Wiek klienta", "Czas sprzedaży", "Id sprzedawcy", "Typ biletu"};
        CacheSqlTableModel model = new CacheSqlTableModel("select * from bilety", columns, "ORDER BY NR");
        biletyTable.setModel(model);
        biletyTable.removeColumn(biletyTable.getColumnModel().getColumn(0));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        kupBiletButton = new javax.swing.JButton();
        biletyPanel = new javax.swing.JPanel();
        biletyScrollPane = new javax.swing.JScrollPane();
        biletyTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Zoo Bilety");

        kupBiletButton.setText("Kup bilet");
        kupBiletButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kupBiletButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(kupBiletButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        biletyPanel.setLayout(new java.awt.BorderLayout());

        biletyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        biletyScrollPane.setViewportView(biletyTable);

        biletyPanel.add(biletyScrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(biletyPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kupBiletButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kupBiletButtonMouseClicked
        BiletDialog bilet = new BiletDialog(this, rootPaneCheckingEnabled);
        bilet.setLocation(Zoo.getShowPosition2D(bilet));
        bilet.setVisible(true);
    }//GEN-LAST:event_kupBiletButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiletyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiletyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiletyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiletyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiletyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel biletyPanel;
    private javax.swing.JScrollPane biletyScrollPane;
    private javax.swing.JTable biletyTable;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton kupBiletButton;
    // End of variables declaration//GEN-END:variables
}
