/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zoo;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static zoo.Zoo.getShowPosition2;

/**
 *
 * @author akamojo
 */
public class OcenyFrame extends javax.swing.JFrame {

    private int numer;

    public int getNumer() {
        return numer;
    }

    public void setNumer(int numer) {
        this.numer = numer;
    }

    /**
     * Creates new form OcenyFrame
     */
    public OcenyFrame() {
        initComponents();
        setIconImage(Zoo.getIcon());
    }

    public void refresh() {
        String[] columns = new String[]{"Numer", "Gwiazdki", "Czas wystawienia", "Komentarz", "Numer Biletu", "Numer Wybiegu", "Chip zwierzęcia"};
        CacheSqlTableModel model = new CacheSqlTableModel("select * from oceny where numer_biletu = " + Integer.toString(this.numer), columns, "ORDER BY NUMER_OCENY");
        ocenyTable.setModel(model);
        ocenyTable.removeColumn(ocenyTable.getColumnModel().getColumn(0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        addOcenaButton = new javax.swing.JButton();
        ocenyPanel = new javax.swing.JPanel();
        ocenyScrollPane = new javax.swing.JScrollPane();
        ocenyTable = new javax.swing.JTable();
        linkPanel = new javax.swing.JPanel();
        linkButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Twoje oceny");

        addOcenaButton.setText("Dodaj ocenę");
        addOcenaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addOcenaButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(addOcenaButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        ocenyPanel.setLayout(new java.awt.BorderLayout());

        ocenyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        ocenyTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ocenyTableMouseClicked(evt);
            }
        });
        ocenyScrollPane.setViewportView(ocenyTable);

        ocenyPanel.add(ocenyScrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(ocenyPanel, java.awt.BorderLayout.CENTER);

        linkButton.setText("Wyświetl dostępne zwierzęta i wybiegi");
        linkButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkButtonMouseClicked(evt);
            }
        });
        linkPanel.add(linkButton);

        getContentPane().add(linkPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addOcenaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addOcenaButtonMouseClicked
        OcenaFrame o = new OcenaFrame(this);
        o.setLocation(Zoo.getShowPosition2(o));
        o.setNumer(this.numer);
        o.setVisible(true);
    }//GEN-LAST:event_addOcenaButtonMouseClicked

    private void linkButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkButtonMouseClicked
        WybiegiFrame w = new WybiegiFrame();
        w.setLocation(Zoo.getShowPosition2(w));
        w.setVisible(true);
    }//GEN-LAST:event_linkButtonMouseClicked

    private void ocenyTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ocenyTableMouseClicked
        if (evt.getClickCount() == 2) {
            int selectionIndex = ocenyTable.getSelectionModel().getMinSelectionIndex();
            if (selectionIndex >= 0) {
                CacheSqlTableModel tableModel = (CacheSqlTableModel) ocenyTable.getModel();
                int selectedId = tableModel.getSelectedId(ocenyTable.getSelectedRow());
                OcenaFrame o = new OcenaFrame(this);
                o.setLocation(Zoo.getShowPosition2(o));
                o.setNumer(this.numer);
                
                Execute q = new Execute();
                q.ExecuteQuery("SELECT KOMENTARZ FROM OCENY WHERE NUMER_OCENY = " + Integer.toString(selectedId));

                try {
                    q.getRs().next();
                    o.fill(q.getRs().getString(1));
                    o.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(PracownikFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_ocenyTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OcenyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OcenyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OcenyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OcenyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OcenyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOcenaButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton linkButton;
    private javax.swing.JPanel linkPanel;
    private javax.swing.JPanel ocenyPanel;
    private javax.swing.JScrollPane ocenyScrollPane;
    private javax.swing.JTable ocenyTable;
    // End of variables declaration//GEN-END:variables
}
