/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zoo;

import java.awt.event.KeyEvent;
import java.sql.CallableStatement;
import java.sql.SQLException;
import java.sql.Types;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author akamojo
 */
public class OcenyFrame extends javax.swing.JFrame {

    private int numer;

    public int getNumer() {
        return numer;
    }

    public void setNumer(int numer) {
        this.numer = numer;
    }

    /**
     * Creates new form OcenyFrame
     */
    public OcenyFrame() {
        initComponents();
        Zoo.setIconAndCursor(this);
    }

    public void refresh() {
        String[] columns = new String[]{"Numer", "Gwiazdki", "Czas wystawienia", "Komentarz", "Numer Biletu", "Numer Wybiegu", "Chip zwierzęcia"};
        CacheSqlTableModel model = new CacheSqlTableModel("select * from oceny where numer_biletu = " + Integer.toString(this.numer), columns, "ORDER BY NUMER_OCENY");
        ocenyTable.setModel(model);
        ocenyTable.removeColumn(ocenyTable.getColumnModel().getColumn(0));
    }

    public void hide() {
        buttonPanel.setVisible(false);
        linkPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        searchTextField = new javax.swing.JTextField();
        addOcenaButton = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        ocenyPanel = new javax.swing.JPanel();
        ocenyScrollPane = new javax.swing.JScrollPane();
        ocenyTable = new javax.swing.JTable();
        linkPanel = new javax.swing.JPanel();
        linkButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Oceny przypisane do biletu");

        searchTextField.setMinimumSize(new java.awt.Dimension(50, 20));
        searchTextField.setPreferredSize(new java.awt.Dimension(100, 20));
        searchTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchTextFieldKeyPressed(evt);
            }
        });
        buttonPanel.add(searchTextField);

        addOcenaButton.setText("Dodaj ocenę");
        addOcenaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addOcenaButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(addOcenaButton);

        delButton.setText("Usuń ocenę");
        delButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(delButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        ocenyPanel.setLayout(new java.awt.BorderLayout());

        ocenyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        ocenyTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ocenyTableMouseClicked(evt);
            }
        });
        ocenyScrollPane.setViewportView(ocenyTable);

        ocenyPanel.add(ocenyScrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(ocenyPanel, java.awt.BorderLayout.CENTER);

        linkButton.setText("Wyświetl dostępne zwierzęta i wybiegi");
        linkButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkButtonMouseClicked(evt);
            }
        });
        linkPanel.add(linkButton);

        getContentPane().add(linkPanel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addOcenaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addOcenaButtonMouseClicked
        OcenaFrame o = new OcenaFrame(this);
        o.setLocation(Zoo.getShowPosition2(o));
        o.setNumerBiletu(this.numer);
        o.notFillen();
        o.setVisible(true);
    }//GEN-LAST:event_addOcenaButtonMouseClicked

    private void linkButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkButtonMouseClicked
        WybiegiFrame w = new WybiegiFrame();
        w.setLocation(Zoo.getShowPosition2(w));
        w.setVisible(true);
    }//GEN-LAST:event_linkButtonMouseClicked

    private void ocenyTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ocenyTableMouseClicked
        if (evt.getClickCount() == 2) {
            int selectionIndex = ocenyTable.getSelectionModel().getMinSelectionIndex();
            if (selectionIndex >= 0) {
                CacheSqlTableModel tableModel = (CacheSqlTableModel) ocenyTable.getModel();
                int selectedId = tableModel.getSelectedId(ocenyTable.getSelectedRow());
                OcenaFrame o = new OcenaFrame(this);
                o.setLocation(Zoo.getShowPosition2(o));
                o.setNumerBiletu(this.numer);
                o.fill(selectedId);
                o.fillen();
                o.setVisible(true);
            }
        }
    }//GEN-LAST:event_ocenyTableMouseClicked

    private void delButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delButtonMouseClicked
        int selectionIndex = ocenyTable.getSelectionModel().getMinSelectionIndex();
        if (selectionIndex >= 0) {
            CacheSqlTableModel tableModel = (CacheSqlTableModel) ocenyTable.getModel();
            int selectedId = tableModel.getSelectedId(ocenyTable.getSelectedRow());

            int n = JOptionPane.showOptionDialog(JOptionPane.getRootFrame(), "Jesteś pewnien, że chcesz usunąć ocenę?", "Usuń ocenę",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);

            if (n == 0) {
                Execute up = new Execute();
                up.ExecuteUpdate("DELETE FROM OCENY WHERE NUMER_OCENY = " + Integer.toString(selectedId));
                refresh();
            }
        }
    }//GEN-LAST:event_delButtonMouseClicked

    private void searchTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTextFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (searchTextField.getText().isEmpty()) {
                refresh();
            } else {
                try {
                    String[] columns = new String[]{"Numer", "Gwiazdki", "Czas wystawienia", "Komentarz", "Numer Biletu", "Numer Wybiegu", "Chip zwierzęcia"};

                    CallableStatement cstmt = DBSupport.getConn().prepareCall("{? = call GET_SEARCH_QUERY(PATTERN => ?, IN_TABLE_NAME => 'OCENY')}");
                    cstmt.registerOutParameter(1, Types.VARCHAR);
                    cstmt.setString(2, searchTextField.getText().replaceAll("'", "''"));
                    cstmt.execute();
                    String wynik = cstmt.getString(1);

                    CacheSqlTableModel model = new CacheSqlTableModel(wynik + " AND NUMER_BILETU = " + Integer.toString(this.numer), columns, "ORDER BY NUMER_OCENY");
                    ocenyTable.setModel(model);
                    ocenyTable.removeColumn(ocenyTable.getColumnModel().getColumn(0));

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), ex, "Smutax Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_searchTextFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OcenyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OcenyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OcenyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OcenyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OcenyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOcenaButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton delButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton linkButton;
    private javax.swing.JPanel linkPanel;
    private javax.swing.JPanel ocenyPanel;
    private javax.swing.JScrollPane ocenyScrollPane;
    private javax.swing.JTable ocenyTable;
    private javax.swing.JTextField searchTextField;
    // End of variables declaration//GEN-END:variables
}
