/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zoo;

import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static zoo.Zoo.getShowPosition2;

/**
 *
 * @author akamojo
 */
public class RaportFrame extends javax.swing.JFrame {

    private int id;
    private int etat;
    private PracownikFrame parent;
    
    /**
     * Creates new form RaportFrame
     */
    public RaportFrame() {
        initComponents();
    }
    
    public RaportFrame(PracownikFrame parent) {
        this.parent = parent;
        setIconImage(Zoo.getIcon());
        initComponents();
    }
    
    public void setInfo(int id, int etat) {
        this.id = id;
        this.etat = etat;
        if (etat == 0) {
            zwierzePanel.setVisible(false);
            wybiegPanel.setVisible(true);
        } else {
            zwierzePanel.setVisible(true);
            wybiegPanel.setVisible(false);
        }
    }
    
    public void fill(String uwagi) {
        zwierzePanel.setVisible(false);
        wybiegPanel.setVisible(false);
        uwagiTextArea.setText(uwagi);
        uwagiTextArea.setEditable(false);
        buttonPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        linkPanel = new javax.swing.JPanel();
        linkButton = new javax.swing.JButton();
        wybiegPanel = new javax.swing.JPanel();
        wybiegLabel = new javax.swing.JLabel();
        wybiegTextField = new javax.swing.JTextField();
        zwierzePanel = new javax.swing.JPanel();
        zwierzeLabel = new javax.swing.JLabel();
        zwierzeTextField = new javax.swing.JTextField();
        uwagiPanel = new javax.swing.JPanel();
        uwagiLabel = new javax.swing.JLabel();
        uwagiScrollPane = new javax.swing.JScrollPane();
        uwagiTextArea = new javax.swing.JTextArea();
        buttonPanel = new javax.swing.JPanel();
        changeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Raport");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        linkButton.setText("Wyświetl dostępne zwierzęta i wybiegi");
        linkButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkButtonMouseClicked(evt);
            }
        });
        linkPanel.add(linkButton);

        getContentPane().add(linkPanel, new java.awt.GridBagConstraints());

        wybiegPanel.setLayout(new java.awt.GridBagLayout());

        wybiegLabel.setText("Podaj numer wybiegu:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        wybiegPanel.add(wybiegLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        wybiegPanel.add(wybiegTextField, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(wybiegPanel, gridBagConstraints);

        zwierzePanel.setLayout(new java.awt.GridBagLayout());

        zwierzeLabel.setText("Podaj chip zwierzęcia:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        zwierzePanel.add(zwierzeLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        zwierzePanel.add(zwierzeTextField, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(zwierzePanel, gridBagConstraints);

        uwagiPanel.setLayout(new java.awt.GridBagLayout());

        uwagiLabel.setText("Uwagi:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        uwagiPanel.add(uwagiLabel, gridBagConstraints);

        uwagiScrollPane.setMaximumSize(new java.awt.Dimension(37261, 32767));
        uwagiScrollPane.setPreferredSize(new java.awt.Dimension(250, 100));

        uwagiTextArea.setColumns(20);
        uwagiTextArea.setFont(new java.awt.Font("Consolas", 2, 14)); // NOI18N
        uwagiTextArea.setRows(5);
        uwagiTextArea.setMaximumSize(new java.awt.Dimension(1237878917, 2147483647));
        uwagiTextArea.setMinimumSize(new java.awt.Dimension(250, 20));
        uwagiTextArea.setName(""); // NOI18N
        uwagiTextArea.setPreferredSize(new java.awt.Dimension(250, 89));
        uwagiScrollPane.setViewportView(uwagiTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        uwagiPanel.add(uwagiScrollPane, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        getContentPane().add(uwagiPanel, gridBagConstraints);

        changeButton.setText("Zatwierdź");
        changeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeButtonMouseClicked(evt);
            }
        });
        buttonPanel.add(changeButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(buttonPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeButtonMouseClicked
        Execute up = new Execute();
        if (etat == 1) {
            try {
                up.ExecutePreparedQuery("INSERT INTO RAPORTY(PRACOWNICY_ID, UWAGI, ZWIERZETA_CHIP) VALUES(?, ?, ?)");
                ((PreparedStatement) up.getStatement()).setInt(1, id);
                ((PreparedStatement) up.getStatement()).setString(2, uwagiTextArea.getText());
                ((PreparedStatement) up.getStatement()).setInt(3, Integer.parseInt(zwierzeTextField.getText()));
                up.firePreparedUpdate();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), ex, "Smutax Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            try {
                up.ExecutePreparedQuery("INSERT INTO RAPORTY(PRACOWNICY_ID, UWAGI, WYBIEGI_NR) VALUES(?, ?, ?)");
                ((PreparedStatement) up.getStatement()).setInt(1, id);
                ((PreparedStatement) up.getStatement()).setString(2, uwagiTextArea.getText());
                ((PreparedStatement) up.getStatement()).setInt(3, Integer.parseInt(wybiegTextField.getText()));
                up.firePreparedUpdate();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(JOptionPane.getRootFrame(), ex, "Smutax Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        parent.refreshRaporty();
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_changeButtonMouseClicked

    private void linkButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkButtonMouseClicked
        WybiegiFrame w = new WybiegiFrame();
        w.setLocation(getShowPosition2(w));
        w.setVisible(true);
    }//GEN-LAST:event_linkButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RaportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RaportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RaportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RaportFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RaportFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton changeButton;
    private javax.swing.JButton linkButton;
    private javax.swing.JPanel linkPanel;
    private javax.swing.JLabel uwagiLabel;
    private javax.swing.JPanel uwagiPanel;
    private javax.swing.JScrollPane uwagiScrollPane;
    private javax.swing.JTextArea uwagiTextArea;
    private javax.swing.JLabel wybiegLabel;
    private javax.swing.JPanel wybiegPanel;
    private javax.swing.JTextField wybiegTextField;
    private javax.swing.JLabel zwierzeLabel;
    private javax.swing.JPanel zwierzePanel;
    private javax.swing.JTextField zwierzeTextField;
    // End of variables declaration//GEN-END:variables
}
