/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zoo;

import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;
import static zoo.Zoo.getShowPosition2;

/**
 *
 * @author akamojo
 */
public class WybiegiFrame extends javax.swing.JFrame {

    public String[] columnsWybiegi = {"Numer wybiegu", "Typ wybiegu", "Powierzchnia (m2)"};
    public String[] columnsZwierzeta = {"Gatunek", "Plec", "Chip"};
    
    public WybiegiFrame() {
        initComponents();
        setIconImage(Zoo.getIcon());
        
        this.refreshAll();
        wybiegiTable.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int row = wybiegiTable.getSelectedRow();
                if (row != -1) 
                    refreshZwierzeta(wybiegiTable.getValueAt(row, 0).toString());
            }
        });
    }
    
    public void refreshAll() {
        //((CacheSqlTableModel) pracownicyTable.getModel()).fireTableDataChanged();
        CacheSqlTableModel model = new CacheSqlTableModel("select nr, typy_wybiegu_nazwa, powierzchnia from wybiegi", columnsWybiegi, "ORDER BY NR");
        wybiegiTable.setModel(model);
                
        model = new CacheSqlTableModel("select gatunki_nazwa, plec, chip from zwierzeta", columnsZwierzeta, "ORDER BY CHIP");
        zwierzetaTable.setModel(model);
    }
    
    public void refreshZwierzeta(String numerWybiegu) {
        CacheSqlTableModel model = new CacheSqlTableModel("select gatunki_nazwa, plec, chip from zwierzeta"
                + " where wybiegi_nr = " + numerWybiegu, columnsZwierzeta, "ORDER BY CHIP");
        zwierzetaTable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonPanel = new javax.swing.JPanel();
        showAllButton = new javax.swing.JButton();
        addWybiegButton = new javax.swing.JButton();
        removeWybiegButton = new javax.swing.JButton();
        addZwierzeButton3 = new javax.swing.JButton();
        removeZwierzeButton = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        tableScrollPaneWybiegi = new javax.swing.JScrollPane();
        wybiegiTable = new javax.swing.JTable();
        tableScrollPaneZwierzeta = new javax.swing.JScrollPane();
        zwierzetaTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Zoo Wybiegi i zwierzęta");
        setMinimumSize(new java.awt.Dimension(250, 250));
        setPreferredSize(new java.awt.Dimension(1000, 500));

        buttonPanel.setLayout(new java.awt.GridBagLayout());

        showAllButton.setText("Pokaż wszystkie");
        showAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        buttonPanel.add(showAllButton, gridBagConstraints);

        addWybiegButton.setText("Dodaj wybieg");
        addWybiegButton.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        addWybiegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWybiegButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        buttonPanel.add(addWybiegButton, gridBagConstraints);

        removeWybiegButton.setText("Usuń wybieg");
        removeWybiegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeWybiegButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        buttonPanel.add(removeWybiegButton, gridBagConstraints);

        addZwierzeButton3.setText("Dodaj zwierzę");
        addZwierzeButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addZwierzeButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        buttonPanel.add(addZwierzeButton3, gridBagConstraints);

        removeZwierzeButton.setText("Usuń zwierzę");
        removeZwierzeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeZwierzeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        buttonPanel.add(removeZwierzeButton, gridBagConstraints);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        tablePanel.setLayout(new java.awt.GridBagLayout());

        wybiegiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        wybiegiTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wybiegiTableMouseClicked(evt);
            }
        });
        tableScrollPaneWybiegi.setViewportView(wybiegiTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        tablePanel.add(tableScrollPaneWybiegi, gridBagConstraints);

        zwierzetaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        zwierzetaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zwierzetaTableMouseClicked(evt);
            }
        });
        tableScrollPaneZwierzeta.setViewportView(zwierzetaTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        tablePanel.add(tableScrollPaneZwierzeta, gridBagConstraints);

        getContentPane().add(tablePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wybiegiTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wybiegiTableMouseClicked
        
        /*if (evt.getClickCount() == 2) {
            int selectionIndex = wybiegiTable.getSelectionModel().getMinSelectionIndex();
            if (selectionIndex >= 0) {
                CacheSqlTableModel tableModel = (CacheSqlTableModel) wybiegiTable.getModel();
                int selectedId = tableModel.getSelectedId(wybiegiTable.getSelectedRow());
                PracownikFrame prac = new PracownikFrame(this);
                prac.setLocation(getShowPosition2(prac));
                prac.fill(selectedId);
                prac.setVisible(true);
            }
        }*/
    }//GEN-LAST:event_wybiegiTableMouseClicked

    private void showAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllButtonActionPerformed
        this.refreshAll();
    }//GEN-LAST:event_showAllButtonActionPerformed

    private void zwierzetaTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zwierzetaTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_zwierzetaTableMouseClicked

    private void addWybiegButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWybiegButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addWybiegButtonActionPerformed

    private void removeWybiegButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeWybiegButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeWybiegButtonActionPerformed

    private void addZwierzeButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addZwierzeButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addZwierzeButton3ActionPerformed

    private void removeZwierzeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeZwierzeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeZwierzeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PracownicyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PracownicyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PracownicyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PracownicyFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PracownicyFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addWybiegButton;
    private javax.swing.JButton addZwierzeButton3;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton removeWybiegButton;
    private javax.swing.JButton removeZwierzeButton;
    private javax.swing.JButton showAllButton;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JScrollPane tableScrollPaneWybiegi;
    private javax.swing.JScrollPane tableScrollPaneZwierzeta;
    private javax.swing.JTable wybiegiTable;
    private javax.swing.JTable zwierzetaTable;
    // End of variables declaration//GEN-END:variables

}
